ikuko_admin_login:
    pattern:  /secured/login
    defaults: { _controller: IkukoAdminBundle:Security:login }

ikuko_admin_login_check:
    pattern:  /secured/login_check

ikuko_admin_logout:
    pattern:  /admin_logout

ikuko_admin_secured_area:
    pattern:  /secured/hello_cris
    defaults: { _controller: IkukoAdminBundle:Default:index }

ikuko_admin_sliders:
    pattern:  /secured/sliders
    defaults: { _controller: IkukoAdminBundle:Slider:llistaSliders }

ikuko_admin_nou_slider:
    pattern:  /secured/nou_slider
    defaults: { _controller: IkukoAdminBundle:Slider:nouSlider }
    requirements:
        _method:  GET|POST

ikuko_admin_edita_slider:
    pattern:  /secured/edita_slider-{id_slider}
    defaults: { _controller: IkukoAdminBundle:Slider:editaSlider }
    requirements:
        _method:  GET|POST

ikuko_admin_elimina_slider:
    pattern:  /secured/elimina_slider-{id_slider}
    defaults: { _controller: IkukoAdminBundle:Slider:eliminaSlider }
    requirements:
        _method:  GET

ikuko_admin_colleccions:
    pattern:  /secured/colleccions
    defaults: { _controller: IkukoAdminBundle:Colleccio:llistaColleccions }

ikuko_admin_nova_colleccio:
    pattern:  /secured/nova_colleccio
    defaults: { _controller: IkukoAdminBundle:Colleccio:novaColleccio }
    requirements:
        _method:  GET|POST

ikuko_admin_edita_colleccio:
    pattern:  /secured/edita_colleccio-{id_colleccio}
    defaults: { _controller: IkukoAdminBundle:Colleccio:editaColleccio }
    requirements:
        _method:  GET|POST

ikuko_admin_elimina_colleccio:
    pattern:  /secured/elimina_colleccio-{id_colleccio}
    defaults: { _controller: IkukoAdminBundle:Colleccio:eliminaColleccio }
    requirements:
        _method:  GET
        
ikuko_admin_productes:
    pattern:  /secured/productes
    defaults: { _controller: IkukoAdminBundle:Producte:llistaProductes }

ikuko_admin_nou_producte:
    pattern:  /secured/nou_producte
    defaults: { _controller: IkukoAdminBundle:Producte:nouProducte }
    requirements:
        _method:  GET|POST

ikuko_admin_edita_producte:
    pattern:  /secured/edita_producte-{id_producte}
    defaults: { _controller: IkukoAdminBundle:Producte:editaProducte }
    requirements:
        _method:  GET|POST

ikuko_admin_elimina_producte:
    pattern:  /secured/elimina_producte-{id_producte}
    defaults: { _controller: IkukoAdminBundle:Producte:eliminaProducte }
    requirements:
        _method:  GET

ikuko_admin_tags:
    pattern:  /secured/tags
    defaults: { _controller: IkukoAdminBundle:Tag:llistaTags }

ikuko_admin_nou_tag:
    pattern:  /secured/nou_tag
    defaults: { _controller: IkukoAdminBundle:Tag:nouTag }
    requirements:
        _method:  GET|POST

ikuko_admin_edita_tag:
    pattern:  /secured/edita_tag-{id_tag}
    defaults: { _controller: IkukoAdminBundle:Tag:editaTag }
    requirements:
        _method:  GET|POST

ikuko_admin_elimina_tag:
    pattern:  /secured/elimina_tag-{id_tag}
    defaults: { _controller: IkukoAdminBundle:Tag:eliminaTag }
    requirements:
        _method:  GET

ikuko_admin_blogs:
    pattern:  /secured/blogs
    defaults: { _controller: IkukoAdminBundle:Blog:llistaBlogs }

ikuko_admin_nou_blog:
    pattern:  /secured/nou_blog
    defaults: { _controller: IkukoAdminBundle:Blog:nouBlog }
    requirements:
        _method:  GET|POST

ikuko_admin_edita_blog:
    pattern:  /secured/edita_blog-{id_blog}
    defaults: { _controller: IkukoAdminBundle:Blog:editaBlog }
    requirements:
        _method:  GET|POST

ikuko_admin_elimina_blog:
    pattern:  /secured/elimina_blog-{id_blog}
    defaults: { _controller: IkukoAdminBundle:Blog:eliminaBlog }
    requirements:
        _method:  GET

ikuko_admin_categories:
    pattern:  /secured/categories
    defaults: { _controller: IkukoAdminBundle:Categoria:llistaCategories }

ikuko_admin_nova_categoria:
    pattern:  /secured/nova_categoria
    defaults: { _controller: IkukoAdminBundle:Categoria:novaCategoria }
    requirements:
        _method:  GET|POST

ikuko_admin_edita_categoria:
    pattern:  /secured/edita_categoria-{id_categoria}
    defaults: { _controller: IkukoAdminBundle:Categoria:editaCategoria }
    requirements:
        _method:  GET|POST

ikuko_admin_elimina_categoria:
    pattern:  /secured/elimina_categoria-{id_categoria}
    defaults: { _controller: IkukoAdminBundle:Categoria:eliminaCategoria }
    requirements:
        _method:  GET

ikuko_admin_imatges:
    pattern:  /secured/imatges
    defaults: { _controller: IkukoAdminBundle:Imatge:llistaImatges }

ikuko_admin_nova_imatge:
    pattern:  /secured/nova_imatge
    defaults: { _controller: IkukoAdminBundle:Imatge:novaImatge }
    requirements:
        _method:  GET|POST

ikuko_admin_elimina_imatge:
    pattern:  /secured/elimina_imatge-{id_imatge}
    defaults: { _controller: IkukoAdminBundle:Imatge:eliminaImatge }
    requirements:
        _method:  GET

ikuko_admin_llocs:
    pattern:  /secured/llocs
    defaults: { _controller: IkukoAdminBundle:Lloc:llistaLlocs }
    
ikuko_admin_nou_lloc:
    pattern:  /secured/nou_lloc
    defaults: { _controller: IkukoAdminBundle:Lloc:nouLloc }
    requirements:
        _method:  GET|POST

ikuko_admin_edita_lloc:
    pattern:  /secured/edita_lloc-{id_lloc}
    defaults: { _controller: IkukoAdminBundle:Lloc:editaLloc }
    requirements:
        _method:  GET|POST

ikuko_admin_elimina_lloc:
    pattern:  /secured/elimina_lloc-{id_lloc}
    defaults: { _controller: IkukoAdminBundle:Lloc:eliminaLloc }
    requirements:
        _method:  GET

ikuko_admin_comentaris:
    pattern:  /secured/comentaris
    defaults: { _controller: IkukoAdminBundle:Comentari:llistaComentaris }

ikuko_admin_elimina_comentari:
    pattern:  /secured/elimina_comentari-{id_comentari}
    defaults: { _controller: IkukoAdminBundle:Comentari:eliminaComentari }
    requirements:
        _method:  GET
