parameters:
#    ikuko_blog.example.class: Ikuko\BlogBundle\Example

services:
#    ikuko_blog.example:
#        class: %ikuko_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
