ikuko_homepage:
    pattern:  /{_locale}
    defaults: { _controller: IkukoIkukoBundle:Default:index, _locale: ca }
    requirements:
        _method:  GET
        _locale: ca|es

ikuko_colleccio:
    pattern:  /{_locale}/{id}/colleccio_{slug}/pag_{page}
    defaults: { _controller: IkukoIkukoBundle:Colleccio:colleccio, page: 1 }
    requirements:
        _method:  GET
        _locale: ca|es

ikuko_about:
    pattern:  /{_locale}/sobre-mi
    defaults: { _controller: IkukoIkukoBundle:Default:about }
    requirements:
        _method:  GET
        _locale: ca|es

ikuko_contacte:
    pattern:  /{_locale}/contacte
    defaults: { _controller: IkukoIkukoBundle:Default:contacte }
    requirements:
        _method:  GET|POST
        _locale: ca|es

ikuko_productes_tag:
    pattern:  /{_locale}/{id}/colleccio_{slug}/{tag}/pag_{page}
    defaults: { _controller: IkukoIkukoBundle:Colleccio:productesTag, page: 1 }
    requirements:
        _method:  GET
        _locale: ca|es
